
#define byte byte1
#include <math.h>

#include <vector>
#include <valarray>
#include <numeric>   // inner_product
#include <memory>    // unique_ptr
#undef byte

using namespace std;

//#include "sigmoid.inc"
//#include "lstm-layer.inc"
#include "sigmoid.h"
#include "sigmoid.hpp"
#include "lstm-layer.h"
#include "lstm-layer.hpp"
//#include "lstm.inc"

#include "lstm.h"
#include "lstm.hpp"

#include "byte-model.inc"

